server {
    listen 80;
    server_name localhost;

    location / {
        fastcgi_pass notification:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/public_html/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_read_timeout 30s;
    }
}
